<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>UnityMeta.Runtime</AssemblyName>
    <RootNamespace>UnityMeta</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Packages/com.drapnard.unitymeta/Runtime/**/*.cs" />
  </ItemGroup>
</Project>
