using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace UnityMeta.Compiler
{
    [Generator]
    public sealed class AspectManifestGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            Receiver? receiver = context.SyntaxReceiver as Receiver;
            if (receiver == null)
            {
                return;
            }

            var names = new List<string>();

            foreach (ClassDeclarationSyntax declaration in receiver.Classes)
            {
                SemanticModel model = context.Compilation.GetSemanticModel(declaration.SyntaxTree);
                INamedTypeSymbol? symbol = model.GetDeclaredSymbol(declaration) as INamedTypeSymbol;
                if (symbol == null || !IsAspect(symbol))
                {
                    continue;
                }

                names.Add(symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }

            names.Sort(StringComparer.Ordinal);

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("namespace UnityMeta.Generated");
            source.AppendLine("{");
            source.AppendLine("    internal static class AspectManifest");
            source.AppendLine("    {");
            source.AppendLine("        internal static readonly string[] AspectTypes = new string[]");
            source.AppendLine("        {");

            foreach (string name in names)
            {
                source.Append("            \"");
                source.Append(name.Replace("global::", string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\""));
                source.AppendLine("\",");
            }

            source.AppendLine("        };");
            source.AppendLine("    }");
            source.AppendLine("}");

            context.AddSource("UnityMeta.AspectManifest.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        }

        private static bool IsAspect(INamedTypeSymbol symbol)
        {
            INamedTypeSymbol? current = symbol.BaseType;
            while (current != null)
            {
                string name = current.ToDisplayString();
                if (name == "UnityMeta.FieldSetAspectAttribute" ||
                    name == "UnityMeta.FieldGetAspectAttribute" ||
                    name == "UnityMeta.FieldChangeAspectAttribute" ||
                    name == "UnityMeta.MethodAspectAttribute")
                {
                    return true;
                }

                current = current.BaseType;
            }

            return false;
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> Classes { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                ClassDeclarationSyntax? declaration = syntaxNode as ClassDeclarationSyntax;
                if (declaration != null && declaration.BaseList != null)
                {
                    Classes.Add(declaration);
                }
            }
        }
    }
}
