<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>UnityMeta.Weaver.Core</AssemblyName>
    <RootNamespace>UnityMeta.Weaver</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.5" />
    <ProjectReference Include="../UnityMeta.Runtime/UnityMeta.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../../Packages/com.drapnard.unitymeta/Editor/Weaver/Core/**/*.cs" />
  </ItemGroup>
</Project>
