<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/UnityMeta.Runtime/UnityMeta.Runtime.csproj" />
    <ProjectReference Include="../../src/UnityMeta.Weaver.Core/UnityMeta.Weaver.Core.csproj" />
    <ProjectReference Include="../../compiler/UnityMeta.Compiler/UnityMeta.Compiler.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.8.0" />
  </ItemGroup>
</Project>
